apiVersion: v1
kind: ConfigMap
metadata:
  name: localedge-config
  namespace: localedge
data:
  NODE_ENV: "production"
  PORT: "3001"
  FRONTEND_URL: "https://app.localedge.in"
  ADMIN_URL: "https://admin.localedge.in"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
